[package]
name = "simple-transfer-witness"
version = "0.1.0"
edition = "2021"

[dependencies]
arm = { path = "../../../arm", default-features = false }
serde = { version = "1.0.197", default-features = false }
rand = "0.8"
lazy_static = "1.5.0"
hex = "0.4"
