[package]
name = "trivial-logic"
version = "1.0.0"
edition = "2021"

[dependencies]
trivial-logic-methods = { path = "methods" }
risc0-zkvm = "3.0.3"
anoma-rm-risc0 = { path = "../../arm", default-features = false }
