[package]
name = "simple-receive"
version = "0.1.0"
edition = "2021"

[dependencies]
receive-core = { path = "core" }
serde = { version = "1.0.197", default-features = false }
risc0-zkvm = "2.0.2"
aarm = { path = "../../../../aarm" }
kudo-core = { path = "../../kudo_core" }
aarm_core = { path = "../../../../aarm_core" }
