[package]
name = "batch_aggregation"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "3.0.3", features = [
  "std",
  "unstable",
], default-features = false }
arm = { path = "../../../../arm", features = [
  "aggregation_circuit",
], default-features = false }
