[package]
name = "batch_aggregation"
version = "1.0.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "3.0.3", features = [
  "std",
  "unstable",
], default-features = false }
anoma-rm-risc0 = { path = "../../../../arm", features = [
  "aggregation_circuit",
], default-features = false }
bincode = { version = "1.3.3", optional = true }
borsh = { version = "1.5", default-features = false, optional = true }

[features]
default = []
borsh = ["dep:borsh"]
bin = ["dep:bincode"]
