[package]
name = "compliance-guest"
version = "1.0.0"
edition = "2021"

[workspace]

[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-zkvm = { version = "3.0.3", features = [
  "std",
  "unstable",
], default-features = false }
anoma-rm-risc0 = { path = "../../../../arm", features = [
  "compliance_circuit",
], default-features = false }
bincode = { version = "1.3.3", optional = true }
borsh = { version = "1.5", default-features = false, optional = true }

[features]
default = []
borsh = ["dep:borsh"]
bin = ["dep:bincode"]

[patch.crates-io]
# Placing this patch statement in the workspace Cargo.toml will add RISC Zero SHA-256 accelerator
# support for all downstream usages of the `sha2` crate.

# Either risc0_zkvm::sha and sha2 with the patch will use the RISC Zero SHA-256
# accelerator. We're using risc0_zkvm::sha, so we don't need to patch sha2.
# sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.3-risczero.1" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
